# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Docker Login'
      inputs:
        containerRegistry: 'SebugDockerHub'
        command: login

    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'SebugDockerHub'
        repository: 'sebug/course-radio-plan'
        command: build
        dockerfile: '**/Dockerfile'
        tags: '$(Build.BuildId)'

    - task: Docker@2
      displayName: Push docker image
      inputs:
        containerRegistry: 'SebugDockerHub'
        repository: 'sebug/course-radio-plan'
        command: push
        tags: '$(Build.BuildId)'

